ci:
  autofix_prs: true
  autoupdate_schedule: weekly
  autoupdate_commit_msg: 'chore: pre-commit autoupdate'

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: check-json
  - id: check-toml
  - id: check-yaml
  - id: end-of-file-fixer
    exclude: (docs/.*|samples/.*\.json)
  - id: trailing-whitespace
    exclude: |
        (?x)^(
            .bumpversion.cfg
        )$

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.3.4
  hooks:
  - id: ruff
    args: [--fix, --exit-non-zero-on-fix]
  - id: ruff-format

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.9.0
  hooks:
  - id: mypy
    exclude: 'tests'
    additional_dependencies:
    - types-pytz==2022.7.1.2
